// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Force local .env values so stale shell-level DATABASE_URL does not hijack Prisma.
dotenv.config({ override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed:'npx tsx seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
